steps:
  # Build the container image
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "gcr.io/$PROJECT_ID/google-cloud-api-example:$COMMIT_SHA",
        ".",
      ]
  # Push the container image to Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/google-cloud-api-example:$COMMIT_SHA"]
  # Deploy container image to Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      [
        "run",
        "deploy",
        "google-cloud-api-example-service",
        "--image",
        "gcr.io/$PROJECT_ID/google-cloud-api-example:$COMMIT_SHA",
        "--region",
        "southamerica-east1",
        "--allow-unauthenticated",
      ]
images:
  - gcr.io/$PROJECT_ID/google-cloud-api-example:$COMMIT_SHA
