steps:
  # Build the container image
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "gcr.io/$PROJECT_ID/google-cloud-api-example:$COMMIT_SHA",
        ".",
      ]
  # Push the container image to Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/google-cloud-api-example:$COMMIT_SHA"]
  # Deploy container image to Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      [
        "run",
        "deploy",
        "google-cloud-api-example-service",
        "--image",
        "gcr.io/$PROJECT_ID/google-cloud-api-example:$COMMIT_SHA",
        "--region",
        "southamerica-east1",
        "--allow-unauthenticated",
        "--set-env-vars",
        "SECRET=$$SECRET_KEY",
        "--set-env-vars",
        "DEBUG=False",
        "--set-env-vars",
        "GCP_PROJECT_ID=$PROJECT_ID",
        "--set-env-vars",
        "GCP_REGION=southamerica-east1",
        "--set-env-vars",
        "GCP_RUN_SERVICE_NAME=google-cloud-api-example-service",
        "--set-env-vars",
        "GCP_AUTH_SCOPE=https://www.googleapis.com/auth/cloud-platform",
        "--set-env-vars",
        "FIPE_BASE_URL=https://parallelum.com.br/fipe/api/v1",
      ]
    secretEnv: ["SECRET_KEY"]

availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/app-secret-key/versions/latest
      env: "SECRET_KEY"

images:
  - gcr.io/$PROJECT_ID/google-cloud-api-example:$COMMIT_SHA
